[✨feat]: 공통 컴포넌트 Message 구현
1e5i-Shark/algobaro-fe pull request #37
Opened 2024-02-20 03:24 UTC by meowTarae

## 📝 설명
공통 컴포넌트 Message 컴포넌트를 구현했습니다.

## ✅ PR 유형

- [x] 새로운 기능 추가

## 💻 작업 내용

### ✔️ Props
```
/**
 * Message 컴포넌트
 * @param [ padding = '8px' ] - Message 컴포넌트 padding
 * @param [ avatarSize = 'XS' ] - avatar의 크기
 * @param [ avatarSrc = '' ] - avatar의 이미지 주소
 * @param [ avatarShadow = true ] - avatar의 그림자 표시 여부
 * @param [ userName = 'User1' ] - 작성자
 * @param [ fontSize = '1.6rem' ] - 작성자 및 메시지 내용의 폰트 크기
 * @param [ iconSize = 'XS' ] - icon의 크기
 * @param [ comment ] - required, 메시지 내용
 */
```

### 🎨 UI
![스크린샷 2024-02-20 오후 12 15 26](https://github.com/1e5i-Shark/algobaro-fe/assets/85001878/3b082b07-88ec-4a6c-8d83-c6922c119533)

### 🧪 레이아웃 테스트 코드
WelcomePage.tsx
``` tsx
import styled from 'styled-components';

import Message from '@/components/Common/Message/Message';

export default function WelcomePage() {
  const comment =
    'Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow ';
  return (
    <Div>
      <Message comment={comment} />
    </Div>
  );
}
const Div = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh;
  color: black;
  background-color: #f0f0f0;
`;

```

## 💬 PR 포인트

- props의 IconSize는 Icon 컴포넌트 내부에서 사용될 예정입니다.
- 추가되었으면 좋을 props가 있으시다면 말씀 부탁드립니다.

2024-02-21 05:28 UTC, pySoo commented on src/components/Common/Message/Message.style.ts
> +      white-space: pre-wrap;
저도 word-break으로 단어 단위로 줄바꿈을 해보려고 했었는데
break-all 속성은 한중일 언어를 지원하지 않는다고 합니다 😭
keep-all은 반대로 한중일 언어만 지원하는 속성이라고 해서

어떤 언어에 줄바꿈을 적용하면 좋을지
한 번 얘기 나눠보는 것 어떠신가요??
[차이를 정리한 블로그](https://www.codingfactory.net/10658) 공유드립니다~

2024-02-21 10:21 UTC, joyswim commented on src/components/Common/Message/Message.tsx
> +  iconSize = 'XS',
iconSize가 사용되는 부분이 없다고 에러가 뜹니다!

2024-02-21 12:01 UTC, joyswim commented on src/components/Common/Message/Message.style.ts
> +      white-space: pre-wrap;
word-break 속성 대신 `word-wrap: break-word;` 사용하면 좋을 것 같아요.

2024-02-21 12:08 UTC, joyswim commented on src/components/Common/Message/Message.tsx
> +      </MessageContainer>
src가 falsy값인 경우 기본 이미지를 반환하고 있습니다.

2024-02-21 16:58 UTC, harry7435 requested changes
메시지 컴포넌트에서도 Meow를 외치는 인간 고양이 건호님 ㅋㅋㅋㅋ
피드백 확인사항만 체크하시면 될 거 같습니다!

#### 피드백 확인사항
- span 및 p 태그 styled 컴포넌트화 여부 논의
- 단어 분절 처리 여부

2024-02-21 16:58 UTC, harry7435 commented on src/components/Common/Message/Message.tsx
> +  iconSize = 'XS',
건호님이 PR 포인트에서 iconSize를 이후 Icon 컴포넌트에서 사용할 것이라고 하셨네요!

2024-02-21 16:58 UTC, harry7435 commented on src/components/Common/Message/Message.style.ts
> +      white-space: pre-wrap;
```css
word-break: keep-all;
white-space: pre-wrap;
word-wrap: break-word;
```

다음과 같은 코드로 적용하면 수현님이 원하는 방향으로 수정이 될 거 같습니다!

2024-02-21 16:58 UTC, harry7435 commented on src/components/Common/Message/Message.tsx
> +          <span>{userName}</span>
p5;
54번째 줄 span과 57번째 줄의 p 태그는 따로 styled 컴포넌트로 만들지 않은 이유가 있으실까요?
style.ts 파일에서도 따로 `& > p`와 같이 스타일을 지정하신 것으로 확인되는데
userName과 comment와 같은 의미있는 데이터를 담는 태그이면서 커스텀 스타일도 지정해줘야 하므로 styled 컴포넌트로 변환할 필요는 없을까요?

2024-02-21 16:58 UTC, harry7435 commented on src/components/Common/Message/Message.tsx
> +      </MessageContainer>
[관련 Avatar PR 코멘트 링크](https://github.com/1e5i-Shark/algobaro-fe/pull/15#discussion_r1491899922) 첨부드립니다.
이전에 수영님과 의논하여 설정했던 거 같습니다!

2024-02-21 17:00 UTC, harry7435 approved these changes

2024-02-22 01:21 UTC, meowTarae commented on src/components/Common/Message/Message.style.ts
> +      white-space: pre-wrap;
회의 내용 적용
=> 익준님 코드 반영하고, 부모에 width 값을 부여

2024-02-22 02:18 UTC, pySoo commented on src/components/Common/Message/Message.style.ts
> +      width: 98%;
혹시 요부분 98%로 지정해주신 이유가 있을까요?!
좌우 여백은 padding으로도 충분하지 않을까 싶어서 여쭤봅니닷!

2024-02-22 02:22 UTC, meowTarae commented on src/components/Common/Message/Message.tsx
> +          <span>{userName}</span>
좋은 의견입니다~ 현재 css도 적용되고 있으니, 단순히 html 태그보다는 styled-components 를 사용해주는게 좋아보입니다 👍

2024-02-22 02:23 UTC, meowTarae commented on src/components/Common/Message/Message.style.ts
> +      width: 98%;
댓글이 케밥 아이콘의 열 까지 침범하는 것 같길래, 이를 방지하고자 98%로 제한을 두었습니다~

2024-02-22 02:29 UTC, pySoo commented on src/components/Common/Message/Message.style.ts
> +      width: 98%;
오 그렇다면 rem 단위를 사용해보는건 어떨까요?
너비에 %를 주게되면 반응형이 되었을 때 영향을 받게 되어서
해당 영역만큼 rem을 이용해서 고정적인 너비를 빼주는 방법이 있을 것 같습니다~ 

```tsx
width: calc(100% - 0.4rem); // 예시로 0.4를 주었는데 침범하지 않는 정도로만 설정해주면 좋을 것 같습니다!
```

2024-02-22 02:31 UTC, meowTarae commented on src/components/Common/Message/Message.style.ts
> +      width: 98%;
👀 오호! 좋은 아디이어입니다 👍 
말씀처럼 고정된 값으로 수정해보겠습니다~

2024-02-22 02:35 UTC, joyswim approved these changes

2024-02-22 02:46 UTC, merged