[✨feat]: Login Form 구현
1e5i-Shark/algobaro-fe pull request #51
Opened 2024-02-25 13:40 UTC by harry7435

## 📝 설명

로그인에 사용되는 Form을 구현했습니다.
## ✅ PR 유형

- [x] 새로운 기능 추가
- [x] CSS 등 사용자 UI 디자인 변경

## 💻 작업 내용

### LoginForm UI
- 다크모드
![image](https://github.com/1e5i-Shark/algobaro-fe/assets/70748442/a51ed7a1-dcf3-4ce3-8a1d-5c17913b1d21)

- 라이트모드
![image](https://github.com/1e5i-Shark/algobaro-fe/assets/70748442/96ccaf1c-4329-4df3-b589-17a2c61dd069)

### 주요 구현 기능
- 이메일(아이디) 유효성 검사 정규식 수정 및 에러 문구 수정
  - 수정된 정규식
  `/^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-z]+[.]+[a-z]{2,3}$/`
  
![image](https://github.com/1e5i-Shark/algobaro-fe/assets/70748442/3cb81bdd-e9be-4b8c-bd14-d7709c829d39)

- 로그인 정보 유효성 검사 통과 후 로그인 버튼 활성화
![image](https://github.com/1e5i-Shark/algobaro-fe/assets/70748442/e2821a6a-67bd-4bd5-8317-b8d0cd0501a4)

- 아이디 저장 체크박스 추가, 로컬 스토리지에 저장
![image](https://github.com/1e5i-Shark/algobaro-fe/assets/70748442/82a719f6-32aa-497d-a4b1-717c01dbf305)

- 회원가입 이동 링크 추가
- 비밀번호 input이 빈 칸이면 숨김 버튼 안 보이게 구현
![image](https://github.com/1e5i-Shark/algobaro-fe/assets/70748442/38d5d313-9f74-4dc0-9b33-cde11e023bd1)

- LoginForm 전체 width props 추가

## 💬 PR 포인트

- 로그인 api 연동은 아직 500 internal server error가 계속 발생하는 상황이라 백엔드 분들과 의논 및 해결 중입니다.
  - UI 및 사용자 동작 처리 로직만 구현 완료했습니다. 
  
- 디자인이나 UX 적으로 고쳐야 할 점이나 불편한 점이 있다면 알려주세요!
- 디렉터리 구조나 코드 컨벤션 및 파일 분리 등이 잘 되었는지 피드백 부탁드립니다.

2024-02-26 04:28 UTC, joyswim commented on src/components/LoginForm/loginConstants.ts
> +      value: /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-z]+[.]+[a-z]{2,3}$/,
정규식은 백엔드 분들과 통일하신 걸까요?👀

아이디 정규식에서 [0-9a-zA-Z]+로 변경해야 할 것 같습니다. [0-9a-zA-Z]는 괄호 내부에서 1글자만 허용하는 정규식입니다. 1글자로 제한하는 게 아니라면 +(1개 이상) 허용해야 할 것 같습니다.
@ 뒤 도메인 정규식에서 [.]+는 '...'도 허용하기 때문에 [.]으로 수정이 필요할 것 같습니다.

제가 생각하는 정규식은 다음과 같습니다. 위 내용을 읽어보시고 의도에 따라 수정하시면 될 것 같습니다.
`/^[0-9a-zA-Z]+([-_.]?[0-9a-zA-Z]+)*@[0-9a-z]+[.][a-z]{2,3}$/`

2024-02-26 04:34 UTC, joyswim commented on src/components/LoginForm/LoginForm.style.ts
> +      background-color: ${theme.color.transparent_50};
p5: color를 세세하게 적용해주셨네요!

2024-02-26 04:44 UTC, joyswim commented on src/components/LoginForm/LoginForm.tsx
> +  const [isSaveEmail, setIsSaveEmail] = useState(saveEmail ? true : false);
아이디 저장 옵션 좋아요!

2024-02-26 05:32 UTC, joyswim commented on src/components/LoginForm/LoginForm.tsx
> +        loginEmail: saveEmail ? JSON.parse(saveEmail) : '',
p5: useLocalStorage에서 value를 불러올 때 getSnapshot으로 값을 가져오는데 이 때 string값인 경우 JSON.parse()를 해주지 않아도 될 것 같아.

그래도 JSON.parse()를 해주는 게 좋을지는 생각해볼 부분인 것 같아.

2024-02-26 05:34 UTC, pySoo reviewed
react-hook-form과 관련된 함수들이 많아서
처음 사용할 때 헷갈리는 부분이 많은데 금방 적응해서 잘 구현해주신 것 같아요 👍

요부분들만 확인 부탁드리겠습니다!

1. [props 분리](https://github.com/1e5i-Shark/algobaro-fe/pull/51#discussion_r1502031305)
2. [Input의 type 설정](https://github.com/1e5i-Shark/algobaro-fe/pull/51#discussion_r1502037589)
3. [하드코딩된 path 교체](https://github.com/1e5i-Shark/algobaro-fe/pull/51#discussion_r1502037915)

2024-02-26 05:36 UTC, joyswim commented on src/components/LoginForm/LoginForm.style.ts
> +export const SignUpTextLink = styled(NavLink)`
NavLink를 이렇게 사용할 수도 있군요! 배워갑니다.

2024-02-26 05:40 UTC, pySoo commented on src/components/LoginForm/LoginForm.tsx
> +        loginEmail: saveEmail ? JSON.parse(saveEmail) : '',
헉.. 수영님 갑자기 반모를.. 🤭

2024-02-26 08:00 UTC, harry7435 commented on src/components/LoginForm/loginConstants.ts
> +      value: /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-z]+[.]+[a-z]{2,3}$/,
`@` 앞의 `*`이 있어 앞쪽 정규식은 올바르게 된 것 같은데 뒤쪽 도메인 뒤의 `.`에서는 `[.]+`가 맞는 거 같습니다.
수정된 정규식은 `/^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-z]+[.][a-z]{2,3}$/` 인 것 같습니다.
테스트 한 번 더 부탁드려요! @joyswim

2024-02-26 08:10 UTC, harry7435 commented on src/components/LoginForm/LoginForm.tsx
> +        loginEmail: saveEmail ? JSON.parse(saveEmail) : '',
아 그러면 혹시 useLocalStorage의 setValue 함수는 newValue를 string으로만 받는 건가요?
그렇다면 따로 파싱할 필요는 없겠군요!

한 가지 의문사항이라면 만약 그렇게 되면 이후 객체 형태의 데이터를 로컬 스토리지에 저장하려면 사용하는 쪽에서 `JSON.parse`를 통해 setValue의 매개변수에 넣어줘야 하는걸까요?
어떤 게 더 편한 방식인지 정답은 없기에 기존 것을 유지할 지는 같이 의논해보죠!

2024-02-26 08:17 UTC, harry7435 commented on src/components/LoginForm/LoginForm.tsx
> +        loginEmail: saveEmail ? JSON.parse(saveEmail) : '',
parse를 하지 않으니 예를 들어 저장된 아이디가 `"test1234@test.com"`으로 저장되어 있다면
불러올 때 `""`이 그대로 아이디에 문자열로 나타나네요.
반드시 파싱을 거쳐줘야 하는 것 같습니다!

2024-02-26 08:18 UTC, harry7435 commented on src/components/LoginForm/LoginForm.tsx
> +        loginEmail: saveEmail ? JSON.parse(saveEmail) : '',
![image](https://github.com/1e5i-Shark/algobaro-fe/assets/70748442/ae30372a-3b35-468f-825e-99d03d5961cf)

2024-02-26 08:18 UTC, harry7435 commented on src/components/LoginForm/LoginForm.tsx
> +export default function LoginForm({ width = '100%' }: { width?: string }) {
확장성을 대비해 interface로 빼두겠습니다!

2024-02-26 12:59 UTC, meowTarae approved these changes
서버 문제로 구현에 정말 고생 많으셨습니다 👍 

해당 PR은 프록시 설정이 필요할 듯 한데, 혹시 vite.config.ts 파일의 변경 사항은 나중에 올리실 예정이실까요 👀 ?

2024-02-27 04:51 UTC, joyswim commented on src/components/LoginForm/LoginForm.tsx
> +        loginEmail: saveEmail ? JSON.parse(saveEmail) : '',
네 useLocalStorage에서는 string만 받도록 되어 있습니다.
번거로운 작업이라면 로컬스토리지에서 setValue(value: any)로 받아서 내부에서 string처리해주는 방법이 있을 것 같아요.

2024-02-27 05:06 UTC, joyswim commented on src/components/LoginForm/loginConstants.ts
> +      value: /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-z]+[.]+[a-z]{2,3}$/,
@ 앞쪽 [0-9a-zA-Z]([-_.]?[0-9a-zA-Z])* 확인했습니다!
`[.]+` 이 부분은 `abc@hello...kr` 경우에도 입력이 가능해서 [.]으로 말씀드렸었습니다!
현재 정규식도 좋다고 생각합니다. 고생하셨습니다!

2024-02-27 15:59 UTC, harry7435 commented on src/components/LoginForm/loginConstants.ts
> +      value: /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-z]+[.]+[a-z]{2,3}$/,
`[.]+`은 수정했습니다!

2024-02-28 05:42 UTC, pySoo approved these changes
회의에서 나눈 사항들 모두 반영해주셔서 감사합니다!
기능들도 잘 동작하는 것 같습니다 ㅎㅎ
이대로 회원가입까지 쭉쭉 달려보시죠 🤩

2024-02-28 06:49 UTC, pySoo requested changes

2024-02-28 06:49 UTC, pySoo commented on src/components/LoginForm/loginConstants.ts
> +export const SIGNIN_URL = '/v1/auth/sign-in';
익준님 혹시 요 API path들은
services에서 관리하는 것 어떠신가요?

API path들은 하나의 파일에서 관리하는 것이 유지보수하기 좋을 것 같습니다!

위치는 services 하위로 두면 좋을 것 같은데
파일 이름은 어떻게 지으면 좋을까요? endpoint나 apiPath 등이 있을 것 같아유 🤔

2024-02-28 06:49 UTC, pySoo commented on src/services/Auth/signIn.ts
> +}
`SignInResponse`
컨벤션에 맞춰 대문자로 수정 부탁드립니다!

2024-02-28 06:49 UTC, pySoo commented on src/components/LoginForm/LoginForm.tsx
> +
저희 서버 상태 관리는 react-query를 사용하기로 했던 것 같아서
요부분 react-query를 사용하는 hook으로 빼보면 어떨까요? ㅎㅎ

저번 프로젝트에서는 onSuccess prop을 받아서 [이렇게 작성](https://github.com/prgrms-fe-devcourse/FEDC5_MatNam_Ducki/blob/dev/src/hooks/useAuth.ts)했었는데
저희 상황에 맞게 필요한 부분만 가져와서 써도 좋을 것 같아요!

2024-02-28 07:21 UTC, harry7435 commented on src/components/LoginForm/loginConstants.ts
> +export const SIGNIN_URL = '/v1/auth/sign-in';
apiEndPoint.ts로 만들어보겠습니다!

2024-02-28 07:26 UTC, harry7435 commented on src/components/LoginForm/LoginForm.tsx
> +
추후 리팩토링 PR로 작업해보겠습니다!

2024-02-28 07:30 UTC, pySoo approved these changes
수정 감사합니다! query 작업은 리팩토링으로 가시죠!

2024-02-28 07:38 UTC, merged

2024-02-28 15:32 UTC, harry7435 commented on src/components/LoginForm/LoginForm.style.ts
> +import { Button } from '..';
`../`에서 `/`이 생략된게 아닐까 하네요..? 자동완성을 사용해서 의도를 가지고 작성했던 건 아닙니다!

2024-02-28 15:34 UTC, harry7435 commented on src/components/LoginForm/LoginForm.style.ts
> +export const SignUpTextLink = styled(NavLink)`
기존 컴포넌트를 styled 컴포넌트로 커스텀하는 방법 중 하나입니다!